name: CI/CD with Self-Hosted Runner

on:
  push:
    branches:
      - main # Replace with your branch name if different

jobs:
  deploy:
    runs-on: self-hosted # Specify self-hosted runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.17.0" # Update to a compatible version for Next.js

      - name: Verify Node.js version
        run: node -v

      - name: Install dependencies
        run: npm install

      - name: Build the Next.js application
        env:
          NODE_ENV: production
        run: npm run build

      - name: Deploy the application
        
        run: |
          git pull origin main
          npm install
          pm2 reload ecosystem.config.js --update-env
          pm2 start "npm run start" --name "next-app" --update-env
        shell: bash
